### ISSUE TITLE
Add trimming of whitespace to the user creation process

### ISSUE THREAD

**Issue by Necroni** [EricqyHan/MVC-R1-F3-T1-V2#5]
Currently it looks like users can be created with whitepace on either side of their userName. Adjust the appropriate controller/function to trim whitespace before adding the user's name.

**Comment by Isaaclkm** [comment]
I did a pull request for this, and now the username gets saved without white spaces, so if someone creates a username and writes "Brad", then if someone else writes " Brad " the username won't be created as there's someone else with the name "Brad".
